# Generated by Django 2.0.6 on 2019-03-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='picture',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
